authors:
  zhazi:
    name: Zhazi
    description: Creator
    avatar: https://github.com/the-full.png
  BaCl2:
    name: B-a-C-l-2
    description: Creator
    avatar: https://github.com/B-a-C-l-2.png
